# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersettings', '0007_auto_20160226_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField()),
                ('time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersettings.Profile')),
            ],
        ),
    ]
