# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_dri'),
    ]

    operations = [
        migrations.AddField(
            model_name='dri',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersettings.Profile'),
        ),
    ]
