# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_dri_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dri',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
