# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0007_auto_20160226_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
