# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='van der Henk', max_length=255),
        ),
    ]
